# Some placeholder :
# {player} will be replaced by the name of the player
# {world} will be replaced by the world where the player is located
# {message} will be replaced by the message of the player
#
# HEX COLOR CODE (1.16+):
# exemple :
#  \#EFB9F9
# You need the backslash or it will not work
#
# You can use Placeholder API too


#lang : en, fr, de
lang: 'en'

chatformat:
  format: '§e{player} \#EFB9F9=> &r{message}'
join:
  enable: false
  message: '&aWelcome {player} on {......}'
banned-words:
  - stfu
  - ez
  - skillissue
scoreboard:
  enable: false
  title: '&n&lTitleOfTheScoreBoard'
  content:
    - '&1line1'
    - '&2line2'
    - '&3line3'
    - '&4line4'


groupschat:
  french:
    title: "§b[France]"
    permission: "cgp.fr"
  german:
    title: "§6[Deutsch]"
    permission: "cgp.de"
  english:
    title: "&2[English]"
    permission: "cgp.en"


motd:
  enable: false
  motd: '#50FACC &l&n<----ChatPlus MOTD---->'