name: chatplus
version: '${project.version}'
main: org.rammex.chatplus.Chatplus
api-version: '1.16'
depend: [PlaceholderAPI]


commands:
  ctphelp:
    description: "send the list of the commands"
    permission: ctp.help
  ctpadmin:
    description: "Config ingame of the plugin"
    permission: ctp.admin
  ctpreload:
    description: "Reload the config"
    permission: ctp.reload
  csfchat:
    description: "Staff Chat"
    permission: ctp.sfchat
  ctpgp:
    description: "Group Chat"
    permission: ctp.gp
