name: chatplus
version: '${project.version}'
main: org.rammex.chatplus.Chatplus
api-version: '1.16'

commands:
  ctphelp:
    description: "send the list of the commands"
    permission: ctp.help
  ctpadmin:
    description: "Config ingame of the plugin"
    permission: ctp.admin
